import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export async function GET(request: Request) {
  const url = new URL(request.url);
  const authHeader = request.headers.get('authorization');
  
  // Permitir prueba manual con ?test=true
  if (url.searchParams.get('test') !== 'true' && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const newTool = {
      name: `AI Tool ${Math.floor(Math.random() * 1000)}`,
      description: "An incredible AI tool generated by our programmatic SEO engine to save you hours every week. (Simulated Ingestion)",
      affiliate_link: "https://example.com/affiliate",
    };

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!supabaseUrl || !supabaseKey) {
        throw new Error("Missing Supabase configuration");
    }

    const supabase = createClient(supabaseUrl, supabaseKey);
    const { error } = await supabase.from('tools').insert([newTool]);

    if (error) throw error;

    return NextResponse.json({ success: true, inserted: newTool });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
