import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'About Us | Curated AI List',
  description: 'Learn more about Curated AI List, our mission, and how we curate the best artificial intelligence tools for professionals.',
};

export default function AboutPage() {
  return (
    <main className="container" style={{ maxWidth: '800px', margin: '0 auto', paddingTop: '4rem', paddingBottom: '4rem' }}>
      <div style={{ marginBottom: '3rem' }}>
        <Link href="/" style={{ color: 'var(--accent)', textDecoration: 'none' }}>&larr; Back to Directory</Link>
      </div>
      <h1 style={{ fontSize: '3rem', marginBottom: '2rem', background: 'linear-gradient(to right, #fff, #a5b4fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
        About Curated AI List
      </h1>
      
      <div style={{ fontSize: '1.2rem', color: '#ccc', lineHeight: '1.8' }}>
        <p style={{ marginBottom: '1.5rem' }}>
          Welcome to <strong>Curated AI List</strong>, the premier destination for discovering high-leverage artificial intelligence tools.
        </p>

        <p style={{ marginBottom: '1.5rem' }}>
          In a world where new AI applications are launched every single day, it is nearly impossible for businesses and individuals to separate the signal from the noise. Our mission is to cut through the hype and bring you only the most powerful, battle-tested, and genuinely useful AI tools on the market.
        </p>

        <h2 style={{ fontSize: '1.8rem', color: '#fff', marginTop: '3rem', marginBottom: '1rem' }}>How We Curate</h2>
        <p style={{ marginBottom: '1.5rem' }}>
          Our directory is <strong>programmatically curated</strong>. We leverage advanced AI models to scan the web, analyze tool features, and generate objective, unbiased reviews. This means our list is always up-to-date with the absolute bleeding edge of technology, ensuring you never miss out on the next big productivity multiplier.
        </p>

        <h2 style={{ fontSize: '1.8rem', color: '#fff', marginTop: '3rem', marginBottom: '1rem' }}>Copyright & Transparency</h2>
        <p style={{ marginBottom: '1.5rem' }}>
          We believe in the open democratization of knowledge. All of the guides, reviews, and tool descriptions on this platform are <strong>generated by AI and curated by humans</strong>. Because our content is AI-generated, it is completely free from traditional human copyright restrictions. You are free to read, share, and utilize the knowledge you find here without worry.
        </p>

        <div style={{ marginTop: '4rem', padding: '2rem', background: 'rgba(255,255,255,0.05)', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center' }}>
          <h3 style={{ color: '#fff', marginBottom: '1rem' }}>Want to stay ahead of the curve?</h3>
          <p style={{ fontSize: '1rem' }}>Check back every week as our autonomous systems discover and review the latest tools.</p>
        </div>

        <div style={{ textAlign: 'center', fontStyle: 'italic', color: 'var(--primary)', fontWeight: '500', fontSize: '1.2rem', marginTop: '4rem' }}>
          — The Curated AI List Team
        </div>
      </div>
    </main>
  );
}
